CREATE PROCEDURE sp_sumar
       (v_n1 NUMBER, v_n2 NUMBER)
      IS
          v_total NUMBER;
      BEGIN
          v_total := v_n1 + v_n2;
          dbms_output.put_line('El resultado es ' || v_total);
      END sp_sumar(10, 15);
      
CREATE OR REPLACE PROCEDURE sp_bucle
       (v_numero NUMBER)
      IS
          v_total NUMBER;
      BEGIN
        v_total:=0;
          FOR i IN 1..v_numero LOOP
          v_total:=v_total + i;
          END LOOP;
          dbms_output.put_line('La suma es ' || v_total;
      END sp_bucle(20);
      
      
CREATE TABLE libros (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    isbn VARCHAR2(20),
    titulo VARCHAR2(100),
    autor VARCHAR2(100) DEFAULT 'pendiente',
    precio NUMBER(10, 2),
    CONSTRAINT pk_libros PRIMARY KEY (id)
);

DROP TABLE libros;

INSERT INTO libros (isbn, titulo, autor, precio)
VALUES ('9780525536611', 'El Gran Gatsby', 'F. Scott Fitzgerald', 15.99);

INSERT INTO libros (isbn, titulo, autor, precio)
VALUES ('9780061120084', '1984', 'George Orwell', 12.99);

INSERT INTO libros (isbn, titulo, autor, precio)
VALUES ('9780142437230', 'Moby-Dick', 'Herman Melville', 10.99);

INSERT INTO libros (isbn, titulo, autor, precio)
VALUES ('9780062316097', 'Cien años de soledad', 'Gabriel García Márquez', 14.99);

INSERT INTO libros (isbn, titulo, autor, precio)
VALUES ('9780062561029', 'Harry Potter y la piedra filosofal', 'J.K. Rowling', 9.99);


CREATE OR REPLACE PROCEDURE insertar_libro(
    p_titulo IN libros.titulo%TYPE,
    p_autor IN libros.autor%TYPE DEFAULT NULL,
    p_precio IN libros.precio%TYPE,
    p_isbn IN libros.isbn%TYPE
)
IS
BEGIN
    IF p_titulo IS NULL OR p_isbn IS NULL THEN
        RAISE_APPLICATION_ERROR(-20001, 'Debe proporcionar un título y un ISBN para el libro.');
    END IF;
    
    IF p_autor IS NULL THEN
        INSERT INTO libros (isbn, titulo, precio)
        VALUES (p_isbn, p_titulo, p_precio);
    ELSE
        INSERT INTO libros (isbn, titulo, autor, precio)
        VALUES (p_isbn, p_titulo, p_autor, p_precio);
    END IF;
    
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/


BEGIN
    insertar_libro(p_isbn => '9780525536611', p_titulo => 'El Gran Gatsby', p_precio => 15);
END;



SELECT * FROM libros;

CREATE OR REPLACE PROCEDURE sp_libros
AS
CURSOR c_libros IS SELECT titulo, precio FROM libros;
v_titulo libros.titulo%TYPE;
v_precio libros.precio%TYPE;
BEGIN
OPEN c_libros;
FETCH c_libros INTO v_titulo, v_precio;
WHILE c_libros%FOUND LOOP
DBMS_OUTPUT_LINE(v_titulo || v_precio);
FETCH c_libros INTO v_titulo, v_precio;
END LOOP;
CLOSE c_libros;
END sp_libros;

EXECUTE sp_libros;


I_pdf blob;
begin plpdf init();
plpdf. 