-- (1) CREAR UNA BASE DE DATOS

DROP DATABASE IF EXISTS BDGEOMETRIA;
CREATE DATABASE BDGEOMETRIA;

-- (2) USAR UNA BASE DE DATOS

USE BDGEOMETRIA;

-- (3) CREAR UNA TABLA

CREATE TABLE Triangulo (
   id     INT     NOT NULL AUTO_INCREMENT,     
   base   DOUBLE  NOT NULL,
   altura DOUBLE  NOT NULL,
          PRIMARY KEY(id)
);

-- (4) INSERTAR REGISTROS EN UNA TABLA

INSERT INTO Triangulo(base,altura) VALUES(3.24,12.34);
INSERT INTO Triangulo(base,altura) VALUES(1.25,10.41);

-- (5) MOSTRAR TODOS LOS REGISTROS DE UNA TABLA

SELECT * FROM Triangulo;

