SELECT * FROM SYSTEM.a_clientes;
INSERT INTO SYSTEM.A_CLIENTES (ID_CLIENTE,NOMBRE,CIUDAD,FACTURACION)
VALUES (6,'juan','madrid',1000.241578);

alter session set "_ORACLE_SCRIPT"=true;  
-- USER SQL
CREATE USER "CURSO" IDENTIFIED BY "Abc123456*/*"  
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS

-- ROLES
GRANT "DBA" TO "CURSO" WITH ADMIN OPTION;
GRANT "CONNECT" TO "CURSO" WITH ADMIN OPTION;

-- SYSTEM PRIVILEGES